package searcher;

public enum GeoAccuracy {
	UNKNOWN_LOCATION, COUNTRY_LEVEL, REGION_LEVEL, SUBREGION_LEVEL,
	TOWN_LEVEL, POST_CODE_LEVEL, STREET_LEVEL, INTERSECTION_LEVEL,
	ADDRESS_LEVEL, PREMISE_LEVEL
}
